apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: app-logs-pv
  resources:
    requests:
      storage: 1Gi

