@Library('lab23') _

pipeline {
    agent any

    environment {
        IMAGE_NAME = "rabdelrahman3332/jenkins-app:latest"
    }

    stages {
        stage('RunUnitTest') {
            steps {
                script { runUnitTest() }
            }
        }

        stage('BuildApp') {
            steps {
                script { buildApp() }
            }
        }

        stage('BuildImage') {
            steps {
                script { buildImage(env.IMAGE_NAME) }
            }
        }

        stage('ScanImage') {
            steps {
                script { scanImage() }
            }
        }

        stage('PushImage') {
            steps {
                script {
                    // login على Docker Hub باستخدام Jenkins credentials
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', 
                                                     usernameVariable: 'DOCKER_USER', 
                                                     passwordVariable: 'DOCKER_PASS')]) {
                        sh "docker login -u $DOCKER_USER -p $DOCKER_PASS"
                        sh "docker push ${env.IMAGE_NAME}"
                    }
                }
            }
        }

        stage('RemoveImageLocally') {
            steps {
                script { removeImageLocally(env.IMAGE_NAME) }
            }
        }

        stage('DeployOnK8s') {
            steps {
                script { deployOnK8s() }
            }
        }
    }

    post {
        success {
            echo "Pipeline finished successfully!"
        }
        failure {
            echo "Pipeline failed. Check the logs."
        }
    }
}
